<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE socios [
   <!ELEMENT socios (socio)*>
   <!ELEMENT socio ((numero | clave)?, nombre, edad?)>
   <!ELEMENT clave (#PCDATA)>
   <!ELEMENT edad (#PCDATA)>
   <!ELEMENT nombre (#PCDATA)>
   <!ELEMENT numero (#PCDATA)>
]>

<socios>
   <socio>
      <nombre>Ana</nombre>
      <edad>21</edad>
   </socio>
   <socio>
      <numero>598</numero>
      <nombre>Iker</nombre>
      <edad>19</edad>
   </socio>
   <socio>
      <clave>hY75Du</clave>
      <nombre>Iker</nombre>
   </socio>
</socios>
<!-- ERRORES -->
<!-- 
   1: En la declaraci칩n de socio, cambiar "," por "|" -> <!ELEMENT socio ((numero | clave)+, nombre, edad)>
   2: En la declaraci칩n de socio, cambia "+" por "?" -> <!ELEMENT socio ((numero | clave)?, nombre, edad)>
   3: En la declaraci칩n de socio, a침adir ? al elemento edad ->    <!ELEMENT socio ((numero | clave)?, nombre, edad?)>

 -->