<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE geografia [
   <!ELEMENT geografia (paises, ciudades)>
   <!ELEMENT paises (pais)*>
      <!ELEMENT pais (#PCDATA)>
         <!ATTLIST pais codpais ID #REQUIRED>
   <!ELEMENT ciudades (ciudad)*>
      <!ELEMENT ciudad (#PCDATA)>
         <!ATTLIST ciudad pais IDREF #IMPLIED>
]>

<geografia>
   <paises>
      <pais codpais="ID1">Argentina</pais>
      <pais codpais="ID2">Austria</pais>
      <pais codpais="ID3">Japón</pais>
      <pais codpais="ID4">Noruega</pais>
      <pais codpais="ID5">España</pais>
   </paises>
   <ciudades>
      <ciudad pais="ID3">Osaka</ciudad>
      <ciudad pais="ID4">Oslo</ciudad>
      <ciudad pais="ID5">Sevilla</ciudad>
      <ciudad pais="ID3">Tokio</ciudad>
      <ciudad pais="ID2">Viena</ciudad>
   </ciudades>
</geografia>