<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE declaraciones [
<<<<<<< HEAD:XML/P5.10 DTD atributos - Corregir errores de validaci贸n II (Evaluable)/declaraciones.xml
   <!ELEMENT declaraciones (#PCDATA | consonante | tipo_de_dato | variable)*>
=======
<!ELEMENT declaraciones (consonante | tipo_de_dato | variable)*>
>>>>>>> 0a45fc874045e0b518001d79687a860ff9cecde9:XML/Ejercicios XML/P5.10 DTD atributos - Corregir errores de validaci贸n II (Evaluable)/declaraciones.xml
   <!ELEMENT consonante (#PCDATA)>
   <!ATTLIST consonante valor CDATA #IMPLIED>
   <!ELEMENT tipo_de_dato (#PCDATA)>
   <!ELEMENT variable (#PCDATA)>
<<<<<<< HEAD:XML/P5.10 DTD atributos - Corregir errores de validaci贸n II (Evaluable)/declaraciones.xml
   <!ATTLIST variable tipo CDATA #IMPLIED>
=======
      <!ATTLIST variable tipo CDATA >
>>>>>>> 0a45fc874045e0b518001d79687a860ff9cecde9:XML/Ejercicios XML/P5.10 DTD atributos - Corregir errores de validaci贸n II (Evaluable)/declaraciones.xml
]>
<!-- Linea 3 falta almenos *
     Linea 8 pone requerido 
-->
<declaraciones>
   <consonante valor="3.141592">PI</consonante>
   <variable tipo="real">radio</variable>
   <variable>area</variable>
   <variable>longitud</variable>
</declaraciones>